language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t heisey/template_react_typescript -f Dockerfile .

script:
  - docker run -e CI=true heisey/template_react_typescript npm run test -- --coverage
